name:                json-handling
version:             0.1.0.0
github:              "SlimTim10/json-handling"
license:             BSD3
author:              "SlimTim10"
maintainer:          "slimtim10@gmail.com"
copyright:           "SlimTim10"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            none

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/SlimTim10/json-handling#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  json-handling-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - json-handling

tests:
  json-handling-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - json-handling
